# Generated by Django 6.0.5 on 2026-05-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('delivered_orders', models.PositiveIntegerField(default=0)),
                ('return_orders', models.PositiveIntegerField(default=0)),
                ('return_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tryon_sessions', models.PositiveIntegerField(default=0)),
                ('cart_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('whatsapp_sent', models.PositiveIntegerField(default=0)),
                ('unsold_alerts', models.PositiveIntegerField(default=0)),
                ('capital_blocked', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('top_product_units', models.PositiveIntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('whatsapp_sent_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('top_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
        ),
    ]
