# Generated by Django 6.0.5 on 2026-05-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='CSM Silks', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='cod_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deal_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_max_days',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_min_days',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='product',
            name='exchange_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='key_highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='return_days',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default='CSM Silks Kanchipuram', max_length=140),
        ),
        migrations.AddField(
            model_name='product',
            name='serviceable_pin_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
