# Generated by Django 6.0.5 on 2026-05-28 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_tone', models.CharField(max_length=20)),
                ('body_type', models.CharField(max_length=20)),
                ('drape_style', models.CharField(max_length=50)),
                ('occasion', models.CharField(blank=True, max_length=80)),
                ('ai_result', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('added_to_cart', models.BooleanField(default=False)),
                ('converted_to_order', models.BooleanField(default=False)),
                ('model_used', models.CharField(default='rules-v1', max_length=80)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='try_on_sessions', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='try_on_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
