# Generated by Django 6.0.5 on 2026-05-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='manual', max_length=60)),
                ('awb_number', models.CharField(blank=True, max_length=100)),
                ('tracking_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='created', max_length=30)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
        ),
    ]
