# Generated by Django 6.0.5 on 2026-05-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_placed', 'Order placed'), ('payment_pending', 'Payment pending'), ('confirmed', 'Confirmed'), ('quality_check', 'Quality check'), ('packed', 'Packed'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('arrived_at_hub', 'Arrived at hub'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('delivery_attempted', 'Delivery attempted'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('return_requested', 'Return requested'), ('returned', 'Returned'), ('refunded', 'Refunded')], max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('happened_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='orders.order')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment')),
            ],
            options={
                'ordering': ['happened_at', 'id'],
            },
        ),
    ]
