# Generated by Django 6.0.5 on 2026-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipmentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='label_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='manifest_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='rto_reason',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rto_initiated', 'RTO initiated'), ('rto_delivered', 'RTO delivered')], default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipmentevent',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Order placed'), ('payment_pending', 'Payment pending'), ('confirmed', 'Confirmed'), ('quality_check', 'Quality check'), ('packed', 'Packed'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('arrived_at_hub', 'Arrived at hub'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('delivery_attempted', 'Delivery attempted'), ('delayed', 'Delayed'), ('rto_initiated', 'RTO initiated'), ('rto_delivered', 'RTO delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return requested'), ('returned', 'Returned'), ('refunded', 'Refunded')], max_length=40),
        ),
    ]
