# Generated by Django 6.0.5 on 2026-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment pending'), ('confirmed', 'Confirmed'), ('quality_check', 'Quality check'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery failed'), ('rto_initiated', 'RTO initiated'), ('rto_delivered', 'RTO delivered'), ('cancelled', 'Cancelled'), ('return_initiated', 'Return initiated'), ('returned', 'Returned'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=30),
        ),
    ]
